//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftUniContests.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contest()
        {
            this.Pictures = new HashSet<Picture>();
        }
    
        public int ContestID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public SoftUniContests.BusinessObjects.Enums.RewardStrategy RewardStrategy { get; set; }
        public SoftUniContests.BusinessObjects.Enums.VotingStrategy VoteStrategy { get; set; }
        public SoftUniContests.BusinessObjects.Enums.ParticipationStrategy ParticipationStrategy { get; set; }
        public SoftUniContests.BusinessObjects.Enums.DeadlineStrategy DeadlineStrategy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Picture> Pictures { get; set; }
    }
}
